# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eeca75884423ea3b6357ac07dd62c115059dc390245ce8afdcc579d70b4208a0ec4644c0dae6b2bd267ae2c2c0fce77d7c1175b88af35d392c03aef7a6157221

test:
  secret_key_base: 432a94591f02e58e0c199d168df2adb05e5fa29f8b66a7fbfa12f814127496bcb39d23a04ba5961ab38739ad2117d4ec4e5281f334c3133c44dafa509cb9ff88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
