# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 177aa4e4e68487c1a3a42f6da99d16a1daf7b55b3c55fc650bae4d181ef271fdfd9831295b0e999c5cdf3485adb26c0325d810276f1f9e08f6059420acc5f55d

test:
  secret_key_base: f2bcd98594108580e3779ed8421743dcb09efff62d85cd6696f0cdc5995c7a7e1819e3682e02a286b0ba5b070e79e4a7e96ffd165ee5f0bd208c54bc8c0dfafd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
