questions = [
              "Use .map to capitalize every name in an array called 'names' and save it into capitalized_names",
              "Use .collect to iterate through an array of hashes called bank_accounts, filtering based on if the 'balance' in each is empty, and save it into the variable most_new_yorkers.",
              "Use .each to iterate through an array of People objects, and output to terminal their first_name, last_name, and an exclamation point",
              "Write the SQL command to create a new database called awesome_movies",
              "Write the SQL command to insert into awesome_movies a movie of your choice",
              "Write a SQL query to get from the database awesome_movies, every movie whose release_year is before 1995",
              "What is the pg gem used for? Why is it useful?",
              "What command do you use to include gems into your Ruby program?",
              "What cmmand do you use to include your own Ruby files into your Ruby program?",
              "What is Rack? How does it fit into writing server apps? Is there a term for it?",
              "What is Sinatra?",
              "If you go to nytimes.com and get redirected to newyorktimes.com, how many HTTP requests get sent from your computer?",
              "Write a Ruby class called Student, who's constrctor takes a name, github, and whose initialize defaults homework grades to F, for 'finished'.",
              "Write the code to instantiate an instance of the Turtle class from the Ninja module.",
              "What is pry? How do we use it?",
              "What is string interpolation?",
              "What is a setter method? What's the shorthand in a Ruby class?",
              "What is a getter method? What's the shorthand in a Ruby class?",
              "What is attr_accessor?",
              "What is the difference between an instance method and a class method?",
              "What is the difference between a class and a module in Ruby?",
              "What is a gem?",
              "What is a gemfile?",
              "What are static files or assets?",
              "What is erb?"
            ]

students = [ "Jacob Shemkovitz",
             "Andres Carter",
             "Steph Nathai",
             "Meiji Chen",
             "Nick Marshall",
             "Jennifer Yien",
             "Brian Deutsch",
             "Edward Petner",
             "Esther Zinn",
             "Harrison Riddell",
             "Victoria Donnelly",
             "Yuka Nagai",
             "Christopher Smith",
             "Jaskaranjit Singh",
             "Pierre Cajuste",
             "Joy Morgan",
             "Pamela Nevins",
             "Zoe Sachs",
             "Eric Kim",
             'Salvatore "Toti" Fanara',
             "Mohamed Elgendy",
             "Raquel Hosein",
             "Matt Morrisey",
             "Calvin Yeung",
             "Josh Bubis"
           ]
